import React, { createRef } from "react";
import { Typeahead } from "react-bootstrap-typeahead";
import "react-bootstrap-typeahead/css/Typeahead.css";
class StepTwo extends React.Component {
  constructor(props) {
    super(props);
    this.desctiption = React.createRef();
    this.bedRoom = React.createRef();
    this.bathRoom = React.createRef();
    this.handleClick = this.handleClick.bind(this);
    this.state = {
      address:[],
      addresses: [],
    };
  }
  hasError(key) {
    return this.state.errors.indexOf(key) !== -1;
  }
  componentDidMount() {
    const arr = [
      "Adilabad",
      "Agra",
      "Ahmedabad",
      "Ahmednagar",
      "Aizawl",
      "Ajitgarh (Mohali)",
      "Ajmer",
      "Akola",
      "Alappuzha",
      "Aligarh",
      "Alirajpur",
      "Allahabad",
      "Almora",
      "Alwar",
      "Ambala",
      "Ambedkar Nagar",
      "Amravati",
      "Amreli district",
      "Amritsar",
      "Anand",
      "Anantapur",
      "Anantnag",
      "Angul",
      "Anjaw",
      "Anuppur",
      "Araria",
      "Ariyalur",
      "Arwal",
      "Ashok Nagar",
      "Auraiya",
      "Aurangabad",
      "Aurangabad",
      "Azamgarh",
      "Badgam",
      "Bagalkot",
      "Bageshwar",
      "Bagpat",
      "Bahraich",
      "Baksa",
      "Balaghat",
      "Balangir",
      "Balasore",
      "Ballia",
      "Balrampur",
      "Banaskantha",
      "Banda",
      "Bandipora",
      "Bangalore Rural",
      "Bangalore Urban",
      "Banka",
      "Bankura",
      "Banswara",
      "Barabanki",
      "Baramulla",
      "Baran",
      "Bardhaman",
      "Bareilly",
      "Bargarh (Baragarh)",
      "Barmer",
      "Barnala",
      "Barpeta",
      "Barwani",
      "Bastar",
      "Basti",
      "Bathinda",
      "Beed",
      "Begusarai",
      "Belgaum",
      "Bellary",
      "Betul",
      "Bhadrak",
      "Bhagalpur",
      "Bhandara",
      "Bharatpur",
      "Bharuch",
      "Bhavnagar",
      "Bhilwara",
      "Bhind",
      "Bhiwani",
      "Bhojpur",
      "Bhopal",
      "Bidar",
      "Bijapur",
      "Bijapur",
      "Bijnor",
      "Bikaner",
      "Bilaspur",
      "Bilaspur",
      "Birbhum",
      "Bishnupur",
      "Bokaro",
      "Bongaigaon",
      "Boudh (Bauda)",
      "Budaun",
      "Bulandshahr",
      "Buldhana",
      "Bundi",
      "Burhanpur",
      "Buxar",
      "Cachar",
      "Central Delhi",
      "Chamarajnagar",
      "Chamba",
      "Chamoli",
      "Champawat",
      "Champhai",
      "Chandauli",
      "Chandel",
      "Chandigarh",
      "Chandrapur",
      "Changlang",
      "Chatra",
      "Chennai",
      "Chhatarpur",
      "Chhatrapati Shahuji Maharaj Nagar",
      "Chhindwara",
      "Chikkaballapur",
      "Chikkamagaluru",
      "Chirang",
      "Chitradurga",
      "Chitrakoot",
      "Chittoor",
      "Chittorgarh",
      "Churachandpur",
      "Churu",
      "Coimbatore",
      "Cooch Behar",
      "Cuddalore",
      "Cuttack",
      "Dadra and Nagar Haveli",
      "Dahod",
      "Dakshin Dinajpur",
      "Dakshina Kannada",
      "Daman",
      "Damoh",
      "Dantewada",
      "Darbhanga",
      "Darjeeling",
      "Darrang",
      "Datia",
      "Dausa",
      "Davanagere",
      "Debagarh (Deogarh)",
      "Dehradun",
      "Deoghar",
      "Deoria",
      "Dewas",
      "Dhalai",
      "Dhamtari",
      "Dhanbad",
      "Dhar",
      "Dharmapuri",
      "Dharwad",
      "Dhemaji",
      "Dhenkanal",
      "Dholpur",
      "Dhubri",
      "Dhule",
      "Dibang Valley",
      "Dibrugarh",
      "Dima Hasao",
      "Dimapur",
      "Dindigul",
      "Dindori",
      "Diu",
      "Doda",
      "Dumka",
      "Dungapur",
      "Durg",
      "East Champaran",
      "East Delhi",
      "East Garo Hills",
      "East Khasi Hills",
      "East Siang",
      "East Sikkim",
      "East Singhbhum",
      "Eluru",
      "Ernakulam",
      "Erode",
      "Etah",
      "Etawah",
      "Faizabad",
      "Faridabad",
      "Faridkot",
      "Farrukhabad",
      "Fatehabad",
      "Fatehgarh Sahib",
      "Fatehpur",
      "Fazilka",
      "Firozabad",
      "Firozpur",
      "Gadag",
      "Gadchiroli",
      "Gajapati",
      "Ganderbal",
      "Gandhinagar",
      "Ganganagar",
      "Ganjam",
      "Garhwa",
      "Gautam Buddh Nagar",
      "Gaya",
      "Ghaziabad",
      "Ghazipur",
      "Giridih",
      "Goalpara",
      "Godda",
      "Golaghat",
      "Gonda",
      "Gondia",
      "Gopalganj",
      "Gorakhpur",
      "Gulbarga",
      "Gumla",
      "Guna",
      "Guntur",
      "Gurdaspur",
      "Gurgaon",
      "Gwalior",
      "Hailakandi",
      "Hamirpur",
      "Hamirpur",
      "Hanumangarh",
      "Harda",
      "Hardoi",
      "Haridwar",
      "Hassan",
      "Haveri district",
      "Hazaribag",
      "Hingoli",
      "Hissar",
      "Hooghly",
      "Hoshangabad",
      "Hoshiarpur",
      "Howrah",
      "Hyderabad",
      "Hyderabad",
      "Idukki",
      "Imphal East",
      "Imphal West",
      "Indore",
      "Jabalpur",
      "Jagatsinghpur",
      "Jaintia Hills",
      "Jaipur",
      "Jaisalmer",
      "Jajpur",
      "Jalandhar",
      "Jalaun",
      "Jalgaon",
      "Jalna",
      "Jalore",
      "Jalpaiguri",
      "Jammu",
      "Jamnagar",
      "Jamtara",
      "Jamui",
      "Janjgir-Champa",
      "Jashpur",
      "Jaunpur district",
      "Jehanabad",
      "Jhabua",
      "Jhajjar",
      "Jhalawar",
      "Jhansi",
      "Jharsuguda",
      "Jhunjhunu",
      "Jind",
      "Jodhpur",
      "Jorhat",
      "Junagadh",
      "Jyotiba Phule Nagar",
      "Kabirdham (Kawardha)",
      "Kadapa",
      "Kaimur",
      "Kaithal",
      "Kakinada",
      "Kalahandi",
      "Kamrup Metropolitan",
      "Kamrup",
      "Kanchipuram",
      "Kandhamal",
      "Kangra",
      "Kanker",
      "Kannauj",
      "Kannur",
      "Kanpur",
      "Kanshi Ram Nagar",
      "Kanyakumari",
      "Kapurthala",
      "Karaikal",
      "Karauli",
      "Karbi Anglong",
      "Kargil",
      "Karimganj",
      "Karimnagar",
      "Karnal",
      "Karur",
      "Kasaragod",
      "Kathua",
      "Katihar",
      "Katni",
      "Kaushambi",
      "Kendrapara",
      "Kendujhar (Keonjhar)",
      "Khagaria",
      "Khammam",
      "Khandwa (East Nimar)",
      "Khargone (West Nimar)",
      "Kheda",
      "Khordha",
      "Khowai",
      "Khunti",
      "Kinnaur",
      "Kishanganj",
      "Kishtwar",
      "Kodagu",
      "Koderma",
      "Kohima",
      "Kokrajhar",
      "Kolar",
      "Kolasib",
      "Kolhapur",
      "Kolkata",
      "Kollam",
      "Koppal",
      "Koraput",
      "Korba",
      "Koriya",
      "Kota",
      "Kottayam",
      "Kozhikode",
      "Krishna",
      "Kulgam",
      "Kullu",
      "Kupwara",
      "Kurnool",
      "Kurukshetra",
      "Kurung Kumey",
      "Kushinagar",
      "Kutch",
      "Lahaul and Spiti",
      "Lakhimpur Kheri",
      "Lakhimpur",
      "Lakhisarai",
      "Lalitpur",
      "Latehar",
      "Latur",
      "Lawngtlai",
      "Leh",
      "Lohardaga",
      "Lohit",
      "Lower Dibang Valley",
      "Lower Subansiri",
      "Lucknow",
      "Ludhiana",
      "Lunglei",
      "Madhepura",
      "Madhubani",
      "Madurai",
      "Mahamaya Nagar",
      "Maharajganj",
      "Mahasamund",
      "Mahbubnagar",
      "Mahe",
      "Mahendragarh",
      "Mahoba",
      "Mainpuri",
      "Malappuram",
      "Maldah",
      "Malkangiri",
      "Mamit",
      "Mandi",
      "Mandla",
      "Mandsaur",
      "Mandya",
      "Mansa",
      "Marigaon",
      "Mathura",
      "Mau",
      "Mayurbhanj",
      "Medak",
      "Meerut",
      "Mehsana",
      "Mewat",
      "Mirzapur",
      "Moga",
      "Mokokchung",
      "Mon",
      "Moradabad",
      "Morena",
      "Mumbai City",
      "Mumbai suburban",
      "Munger",
      "Murshidabad",
      "Muzaffarnagar",
      "Muzaffarpur",
      "Mysore",
      "Nabarangpur",
      "Nadia",
      "Nagaon",
      "Nagapattinam",
      "Nagaur",
      "Nagpur",
      "Nainital",
      "Nalanda",
      "Nalbari",
      "Nalgonda",
      "Namakkal",
      "Nanded",
      "Nandurbar",
      "Narayanpur",
      "Narmada",
      "Narsinghpur",
      "Nashik",
      "Navsari",
      "Nawada",
      "Nawanshahr",
      "Nayagarh",
      "Neemuch",
      "Nellore",
      "New Delhi",
      "Nilgiris",
      "Nizamabad",
      "North 24 Parganas",
      "North Delhi",
      "North East Delhi",
      "North Goa",
      "North Sikkim",
      "North Tripura",
      "North West Delhi",
      "Nuapada",
      "Ongole",
      "Osmanabad",
      "Pakur",
      "Palakkad",
      "Palamu",
      "Pali",
      "Palwal",
      "Panchkula",
      "Panchmahal",
      "Panchsheel Nagar district (Hapur)",
      "Panipat",
      "Panna",
      "Papum Pare",
      "Parbhani",
      "Paschim Medinipur",
      "Patan",
      "Pathanamthitta",
      "Pathankot",
      "Patiala",
      "Patna",
      "Pauri Garhwal",
      "Perambalur",
      "Phek",
      "Pilibhit",
      "Pithoragarh",
      "Pondicherry",
      "Poonch",
      "Porbandar",
      "Pratapgarh",
      "Pratapgarh",
      "Pudukkottai",
      "Pulwama",
      "Pune",
      "Purba Medinipur",
      "Puri",
      "Purnia",
      "Purulia",
      "Raebareli",
      "Raichur",
      "Raigad",
      "Raigarh",
      "Raipur",
      "Raisen",
      "Rajauri",
      "Rajgarh",
      "Rajkot",
      "Rajnandgaon",
      "Rajsamand",
      "Ramabai Nagar (Kanpur Dehat)",
      "Ramanagara",
      "Ramanathapuram",
      "Ramban",
      "Ramgarh",
      "Rampur",
      "Ranchi",
      "Ratlam",
      "Ratnagiri",
      "Rayagada",
      "Reasi",
      "Rewa",
      "Rewari",
      "Ri Bhoi",
      "Rohtak",
      "Rohtas",
      "Rudraprayag",
      "Rupnagar",
      "Sabarkantha",
      "Sagar",
      "Saharanpur",
      "Saharsa",
      "Sahibganj",
      "Saiha",
      "Salem",
      "Samastipur",
      "Samba",
      "Sambalpur",
      "Sangli",
      "Sangrur",
      "Sant Kabir Nagar",
      "Sant Ravidas Nagar",
      "Saran",
      "Satara",
      "Satna",
      "Sawai Madhopur",
      "Sehore",
      "Senapati",
      "Seoni",
      "Seraikela Kharsawan",
      "Serchhip",
      "Shahdol",
      "Shahjahanpur",
      "Shajapur",
      "Shamli",
      "Sheikhpura",
      "Sheohar",
      "Sheopur",
      "Shimla",
      "Shimoga",
      "Shivpuri",
      "Shopian",
      "Shravasti",
      "Sibsagar",
      "Siddharthnagar",
      "Sidhi",
      "Sikar",
      "Simdega",
      "Sindhudurg",
      "Singrauli",
      "Sirmaur",
      "Sirohi",
      "Sirsa",
      "Sitamarhi",
      "Sitapur",
      "Sivaganga",
      "Siwan",
      "Solan",
      "Solapur",
      "Sonbhadra",
      "Sonipat",
      "Sonitpur",
      "South 24 Parganas",
      "South Delhi",
      "South Garo Hills",
      "South Goa",
      "South Sikkim",
      "South Tripura",
      "South West Delhi",
      "Sri Muktsar Sahib",
      "Srikakulam",
      "Srinagar",
      "Subarnapur (Sonepur)",
      "Sultanpur",
      "Sundergarh",
      "Supaul",
      "Surat",
      "Surendranagar",
      "Surguja",
      "Tamenglong",
      "Tarn Taran",
      "Tawang",
      "Tehri Garhwal",
      "Thane",
      "Thanjavur",
      "The Dangs",
      "Theni",
      "Thiruvananthapuram",
      "Thoothukudi",
      "Thoubal",
      "Thrissur",
      "Tikamgarh",
      "Tinsukia",
      "Tirap",
      "Tiruchirappalli",
      "Tirunelveli",
      "Tirupur",
      "Tiruvallur",
      "Tiruvannamalai",
      "Tiruvarur",
      "Tonk",
      "Tuensang",
      "Tumkur",
      "Udaipur",
      "Udalguri",
      "Udham Singh Nagar",
      "Udhampur",
      "Udupi",
      "Ujjain",
      "Ukhrul",
      "Umaria",
      "Una",
      "Unnao",
      "Upper Siang",
      "Upper Subansiri",
      "Uttar Dinajpur",
      "Uttara Kannada",
      "Uttarkashi",
      "Vadodara",
      "Vaishali",
      "Valsad",
      "Varanasi",
      "Vellore",
      "Vidisha",
      "Viluppuram",
      "Virudhunagar",
      "Visakhapatnam",
      "Vizianagaram",
      "Vyara",
      "Warangal",
      "Wardha",
      "Washim",
      "Wayanad",
      "West Champaran",
      "West Delhi",
      "West Garo Hills",
      "West Kameng",
      "West Khasi Hills",
      "West Siang",
      "West Sikkim",
      "West Singhbhum",
      "West Tripura",
      "Wokha",
      "Yadgir",
      "Yamuna Nagar",
      "Yanam",
      "Yavatmal",
      "Zunheboto",
    ];
    this.setState({
      addresses: arr,
    });
  }
  handleClick = (e) => {
    e.preventDefault();
    const doc = {
      desc: this.desctiption.current.value,
      bedRoom: this.bedRoom.current.value,
      bathRoom: this.bathRoom.current.value,
      address: this.state.address,
    };
    console.log(doc);
    this.props.setDoc(doc)
    this.props.handleChange(2);
  };
  render() {
    return (
      <div>
        <h1 className="badge badge-secondary">Step Two</h1>
        <form
          id="formFields"
          className="row was-validated"
          data-bv-feedbackicons-valid="glyphicon glyphicon-ok"
          data-bv-feedbackicons-invalid="glyphicon glyphicon-remove"
          data-bv-feedbackicons-validating="glyphicon glyphicon-refresh"
        >
          <table className="w-50 mx-auto">
            <tbody>
              <tr>
                <td style={{ textAlign: "right" }}>
                  <span>Enter Address: </span>
                </td>
                <td style={{ textAlign: "left" }} className="form-group">
                  <Typeahead
                    id="basic-typeahead-single"
                    labelKey="address"
                    onChange={(selected) => {
                      this.setState({address:selected});
                    }}
                    options={this.state.addresses}
                    placeholder="Choose a state..."
                    selected={this.state.address}
                  />
                </td>
              </tr>
              <tr>
                <td style={{ textAlign: "right" }}>
                  <span>BedRoom: </span>
                </td>
                <td style={{ textAlign: "left" }} className="form-group">
                  <input
                    type="number"
                    ref={this.bedRoom}
                    className="form-control"
                    maxlength="10"
                    required
                    data-bv-stringlength-message="The value must be less than 10"
                  ></input>
                </td>
              </tr>
              <tr>
                <td style={{ textAlign: "right" }}>
                  <span>BathRoom: </span>
                </td>
                <td style={{ textAlign: "left" }} className="form-group">
                  <input
                    type="number"
                    ref={this.bathRoom}
                    className="form-control"
                    maxlength="5"
                    required
                    data-bv-stringlength-message="The value must be less than 5"
                  ></input>
                </td>
              </tr>
              <tr>
                <td style={{ textAlign: "right" }}>
                  <span>Description: </span>
                </td>
                <td style={{ textAlign: "left" }} className="form-group">
                  <input
                    type="text"
                    ref={this.desctiption}
                    className="form-control"
                  ></input>
                </td>
              </tr>
              <tr>
                <td></td>
                <td>
                  <button
                    type="button"
                    className="btn btn-success"
                    onClick={this.handleClick}
                  >
                    Step Three
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
          <br />
          <br />
        </form>
      </div>
    );
  }
}
export default StepTwo;
